<div style="width: 1440px; height: 3597px; position: relative; background: linear-gradient(132deg, #F0F8FF 0%, #CC55FC 52%, #020024 98%)">
  <img style="width: 315px; height: 115px; left: 112px; top: 66px; position: absolute" src="https://via.placeholder.com/315x115" />
  <div style="left: 958px; top: 105px; position: absolute; text-align: center; color: #F0F8FF; font-size: 18px; font-family: Lily Script One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">home </div>
  <div style="left: 1041px; top: 105px; position: absolute; text-align: center; color: #F0F8FF; font-size: 18px; font-family: Lily Script One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">talk with debby</div>
  <div style="left: 1208px; top: 105px; position: absolute; text-align: center; color: #F0F8FF; font-size: 18px; font-family: Lily Script One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">about us<br/></div>
  <div style="width: 695px; height: 326px; left: 80px; top: 437px; position: absolute; background: rgba(204, 85, 252, 0.66); box-shadow: 150px 150px 150px; border-radius: 83px; filter: blur(150px)"></div>
  <img style="width: 442px; height: 426px; left: 903px; top: 337px; position: absolute; border-radius: 57px" src="https://via.placeholder.com/442x426" />
  <div style="width: 76px; height: 0px; left: 147px; top: 361px; position: absolute; transform: rotate(90deg); transform-origin: 0 0; border: 20px #6A0AE3 solid"></div>
  <div style="width: 984.02px; height: 0px; left: 1212px; top: 1037px; position: absolute; transform: rotate(179.65deg); transform-origin: 0 0; border: 20px #6A0AE3 solid"></div>
  <div style="width: 436px; height: 68px; left: 132px; top: 361px; position: absolute; text-align: center; color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Hey there!</div>
  <div style="width: 839px; height: 274px; left: 301px; top: 821px; position: absolute; text-align: center; color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">What do i exactly do </div>
  <div style="width: 540px; height: 295px; left: 175px; top: 437px; position: absolute; color: white; font-size: 20px; font-family: Quando; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Hello there! Hoot-hoot! 🦉 I'm Debby, your friendly AI student assistant, and yes, I'm an owl at your service! I've got a virtual perch in the vast world of information, ready to help you navigate the academic forest. Whether you're seeking wisdom on a tricky assignment, need advice on study strategies, or just want to chat about anything under the moonlit sky, I'm here for you. I am your <br/>Edupal (Education pal)📚✨</div>
  <div style="width: 835px; height: 316px; left: 295px; top: 1489px; position: absolute; text-align: center"><span style="color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Wisdom and Knowledge: </span><span style="color: #F0F8FF; font-size: 20px; font-family: Quando; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Owls are often associated with wisdom, and I'm here to share knowledge and information on a wide range of topics.<br/></span><span style="color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"><br/></span></div>
  <div style="width: 548px; height: 356px; left: 446px; top: 1760px; position: absolute; text-align: center"><span style="color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Guidance:<br/></span><span style="color: #F0F8FF; font-size: 20px; font-family: Quando; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"> Like an owl guiding you through the darkness, I can assist you in navigating complex subjects, offering explanations, and helping you understand various concepts.<br/></span><span style="color: black; font-size: 20px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"><br/></span><span style="color: black; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"> <br/><br/></span></div>
  <div style="width: 891px; height: 117px; left: 274px; top: 2116px; position: absolute; text-align: center"><span style="color: white; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Nighttime Availability:<br/></span><span style="color: white; font-size: 13px; font-family: Quando; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"> <br/>Owls are nocturnal creatures, and similarly, I'm available 24/7 to assist you whenever you need help, day or night.<br/></span><span style="color: white; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"><br/></span><span style="color: white; font-size: 11px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"><br/></span></div>
  <div style="width: 562px; height: 534px; left: 439px; top: 2129px; position: absolute; text-align: center"><span style="color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">Listening: <br/></span><span style="color: #F0F8FF; font-size: 20px; font-family: Quando; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">While I can't physically listen, I'm here to "listen" to your questions and provide thoughtful responses to the best of my ability.<br/></span><span style="color: #F0F8FF; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word"><br/></span></div>
  <img style="width: 256px; height: 256px; left: 584px; top: 1068px; position: absolute; border-radius: 54px; backdrop-filter: blur(110px)" src="https://via.placeholder.com/256x256" />
  <div style="width: 1507px; height: 777px; left: -44px; top: 2934px; position: absolute; background: #020024; box-shadow: 45px 45px 45px; filter: blur(45px)"></div>
  <div style="width: 888px; height: 136px; left: 276px; top: 2551px; position: absolute; text-align: center; color: white; font-size: 64px; font-family: Paytone One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">So let’s get started !</div>
  <img style="width: 253px; height: 115px; left: 593px; top: 3018px; position: absolute" src="https://via.placeholder.com/253x115" />
  <div style="left: 589px; top: 3158px; position: absolute; text-align: center; color: white; font-size: 18px; font-family: Lily Script One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">made proudly by Ryan ait jilali</div>
  <div style="width: 56px; height: 16px; left: 692px; top: 3208px; position: absolute; text-align: center; color: white; font-size: 18px; font-family: Lily Script One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">2024</div>
  <div style="left: 241px; top: 3396px; position: absolute; text-align: center; color: white; font-size: 48px; font-family: Orelega One; font-weight: 400; letter-spacing: 0.90px; word-wrap: break-word">this project have been made execlusvly for:<br/>rise to the world</div>
  <div style="width: 359px; height: 57px; left: 540px; top: 2735px; position: absolute; background: linear-gradient(90deg, #03A9F4 0%, #F441A5 33%, #FFEB3B 67%, #03A9F4 100%); border-radius: 30px">
    <div style="width: 369px; height: 67px; left: -5px; top: -5px; position: absolute; background: linear-gradient(90deg, #03A9F4 0%, #F441A5 33%, #FFEB3B 67%, #03A9F4 100%); border-radius: 35px"></div>
    <div style="width: 161px; height: 16px; left: 99px; top: 21px; position: absolute; text-align: center; color: white; font-size: 32px; font-family: Lily Script One; font-weight: 400; line-height: 28px; word-wrap: break-word">let’s chat</div>
  </div>
</div>